FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Codeblaze.SemanticKernel.Api/Codeblaze.SemanticKernel.Api.csproj", "Codeblaze.SemanticKernel.Api/"]
RUN dotnet restore "Codeblaze.SemanticKernel.Api/Codeblaze.SemanticKernel.Api.csproj"
COPY . .
WORKDIR "/src/Codeblaze.SemanticKernel.Api"
RUN dotnet build "Codeblaze.SemanticKernel.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Codeblaze.SemanticKernel.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Codeblaze.SemanticKernel.Api.dll"]
